import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Progressbar from "@/components/progressbar";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "EJUST IEEE Student Branch",
  description: "Generated by Aliaa & Fady",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Progressbar />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
